/* Automatically generated by configure - do not modify */
#include "config-host.h"
#ifdef TARGET_ARCH_mips
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-mips"
#define TARGET_ARCH "mips"
#define TARGET_MIPS 1
#define TARGET_PHYS_ADDR_BITS  64
#endif
#ifdef TARGET_ARCH_arm
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-arm"
#define TARGET_ARCH "arm"
#define TARGET_ARM 1
#define TARGET_PHYS_ADDR_BITS  32
#endif
#define CONFIG_TRACE 1
#define CONFIG_NAND 1
#define CONFIG_SHAPER 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_SDL 1
#ifndef _WIN32
#define CONFIG_NAND_LIMITS 1
#endif
